import type { Metadata } from "next";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";

export const metadata: Metadata = { title: "Privacidad", description: "Cómo trata Hypermociones los datos locales y sincronizados del usuario." };

export default function PrivacyPage() {
  return <AppShell active="privacy"><article className="legal-page"><header><p className="eyebrow">Versión técnica · 18 de agosto de 2026</p><h1>Privacidad</h1><p>Puedes utilizar Hypermociones sin cuenta. La cuenta y la copia entre dispositivos son opcionales.</p></header><section><h2>Uso sin cuenta</h2><p>Mi equipo, alineaciones, historial editorial, proyecciones, partes, seguimiento, escenarios, preferencias y precios se guardan en el almacenamiento local del navegador. Puedes exportarlos, restaurarlos o borrarlos desde <Link href="/settings/data">Datos locales</Link>.</p></section><section><h2>Cuenta y sincronización</h2><p>Si accedes con ChatGPT, tratamos el identificador de usuario, correo y nombre proporcionados por el servicio de identidad. Solo guardamos una copia de tus datos locales cuando pulsas expresamente «Sincronizar este dispositivo». La transmisión usa HTTPS; Hypermociones no recibe ni almacena tu contraseña de ChatGPT.</p></section><section><h2>Control y eliminación</h2><p>Desde <Link href="/account">Cuenta y sincronización</Link> puedes sustituir o restaurar la copia, cerrar sesión y eliminar el perfil junto con la copia remota. Esta última acción no borra automáticamente el contenido local de tus dispositivos.</p></section><section><h2>Fuentes y servicios externos</h2><p>Los enlaces a fuentes u otros sitios tienen sus propias políticas. La autenticación está gestionada por ChatGPT y el almacenamiento remoto por la infraestructura de alojamiento configurada para el proyecto.</p></section><section><h2>Analítica y publicidad</h2><p>Esta versión no integra publicidad ni analítica de comportamiento. Si se incorporan, esta política deberá actualizarse antes de activarlas.</p></section><p className="legal-note">Borrador técnico pendiente de identidad legal del responsable, canal de privacidad, plazos de conservación y revisión jurídica antes de un lanzamiento comercial.</p></article></AppShell>;
}
