"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { isMyFantasyTeam, myTeamStorageKey } from "@/domain/fantasy-team";
import type { FixtureListItem } from "@/domain/fixture";
import { lineupChanges, lineupHistoryStorageKey, parseLineupHistory } from "@/domain/lineup-history";
import type { PlayerListItem, TeamSummary } from "@/domain/player";
import { useRecommendations } from "./use-recommendations";

function countdown(kickoffAt: string) { const delta = new Date(kickoffAt).getTime() - Date.now(); if (delta <= 0) return "Jornada iniciada"; const hours = Math.floor(delta / 3_600_000); return `${Math.floor(hours / 24)}d ${hours % 24}h`; }
export function GameweekCenter({ fixtures, players, teams, round }: { fixtures: FixtureListItem[]; players: PlayerListItem[]; teams: TeamSummary[]; round: number }) {
  const { recommendations, byPlayer, editorialCount } = useRecommendations(players, teams, round);
  const [myIds, setMyIds] = useState<Set<string>>(new Set());
  const [historyChanges, setHistoryChanges] = useState(0);
  const [remaining, setRemaining] = useState(() => fixtures[0] ? countdown(fixtures[0].kickoffAt) : "Sin horario");
  useEffect(() => { const frame = window.requestAnimationFrame(() => { const raw = localStorage.getItem(myTeamStorageKey); if (raw) try { const value: unknown = JSON.parse(raw); if (isMyFantasyTeam(value)) setMyIds(new Set(value.squad.map((item) => item.playerId))); } catch { /* Ignore invalid local state. */ } let changes = 0; for (const team of teams) { const history = parseLineupHistory(localStorage.getItem(lineupHistoryStorageKey(team.id, round)), team.id, round); const current = history.revisions.at(-1); if (current) changes += lineupChanges(history.revisions.at(-2), current).length; } setHistoryChanges(changes); }); return () => window.cancelAnimationFrame(frame); }, [teams, round]);
  useEffect(() => { if (!fixtures[0]) return; const update = () => setRemaining(countdown(fixtures[0].kickoffAt)); const timer = window.setInterval(update, 60_000); return () => window.clearInterval(timer); }, [fixtures]);
  const byTeam = useMemo(() => { const teamByPlayer = new Map(players.map((player) => [player.id, player.team.id])); const grouped = new Map(teams.map((team) => [team.id, [] as typeof recommendations])); for (const item of recommendations) { if (item.startingProbability === null) continue; const teamId = teamByPlayer.get(item.playerId); if (teamId && (grouped.get(teamId)?.length ?? 0) < 5) grouped.get(teamId)?.push(item); } return grouped; }, [teams, recommendations, players]);
  const playerById = new Map(players.map((player) => [player.id, player]));
  const myAlerts = [...myIds].flatMap((id) => { const recommendation = byPlayer.get(id); const player = playerById.get(id); return recommendation && player && (recommendation.startingProbability ?? 0) < 60 ? [{ player, recommendation }] : []; });
  return <><section className="gameweek-hero"><div><p className="eyebrow">Centro de jornada · J{round}</p><h1>Todo antes del cierre.</h1><p>Partidos, confianza editorial, cambios y riesgos de tu plantilla en una sola lectura.</p></div><div><span>Primer partido</span><strong>{remaining}</strong><small>{fixtures[0] ? new Date(fixtures[0].kickoffAt).toLocaleString("es-ES", { dateStyle: "medium", timeStyle: "short" }) : "Pendiente"}</small></div></section><div className="gameweek-kpis"><div><span>Partidos</span><strong>{fixtures.length}</strong></div><div><span>Confianza editorial</span><strong>{editorialCount}</strong></div><div><span>Cambios detectados</span><strong>{historyChanges}</strong></div><div className={myAlerts.length ? "alert" : ""}><span>Alertas Mi equipo</span><strong>{myAlerts.length}</strong></div></div>{myAlerts.length > 0 && <section className="gameweek-alerts"><p className="eyebrow">Revisar antes del cierre</p>{myAlerts.map(({ player, recommendation }) => <Link href={`/player/${player.slug}`} key={player.id}><strong>{player.name}</strong><span>{recommendation.startingProbability ?? "—"}% · Tier {recommendation.tier}</span></Link>)}</section>}<div className="gameweek-matches">{fixtures.map((fixture) => <article key={fixture.id}><header><time>{new Date(fixture.kickoffAt).toLocaleDateString("es-ES", { weekday: "short", day: "2-digit", month: "short" })}</time><strong>{fixture.homeTeam.shortName} <i>vs</i> {fixture.awayTeam.shortName}</strong><Link href={`/lineups?round=${round}`}>Alineaciones →</Link></header><div>{[fixture.homeTeam, fixture.awayTeam].map((team) => <section key={team.id}><h2>{team.name}</h2>{(byTeam.get(team.id) ?? []).map((item) => { const player = playerById.get(item.playerId)!; return <Link href={`/player/${player.slug}`} key={item.playerId}><span className={`tier-badge tier-${item.tier.replace("+", "plus").toLowerCase()}`}>{item.tier}</span><strong>{player.name}</strong><b>{item.startingProbability}%</b></Link>; })}{!(byTeam.get(team.id)?.length) && <p>Sin porcentajes: edita la alineación para añadir confianza.</p>}</section>)}</div></article>)}</div></>;
}
