"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { FixtureListItem } from "@/domain/fixture";
import type { PlayerListItem, TeamSummary } from "@/domain/player";
import { useRecommendations } from "./use-recommendations";
import { useWatchlist } from "./use-watchlist";

const metric = (value: number | null, decimals = 0) => value === null ? "—" : value.toFixed(decimals);
export function PlayerComparator({ players, teams, fixtures, round }: { players: PlayerListItem[]; teams: TeamSummary[]; fixtures: FixtureListItem[]; round: number }) {
  const [selected, setSelected] = useState<string[]>(players.slice(0, 2).map((player) => player.id));
  const { byPlayer: recommendationById } = useRecommendations(players, teams, round);
  const { watched, toggle } = useWatchlist();
  const selectedPlayers = selected.flatMap((id) => [players.find((player) => player.id === id)].filter(Boolean) as PlayerListItem[]);
  const upcoming = useMemo(() => new Map(teams.map((team) => [team.id, fixtures.filter((fixture) => fixture.homeTeam.id === team.id || fixture.awayTeam.id === team.id).sort((a, b) => (a.round ?? 99) - (b.round ?? 99)).slice(0, 5)])), [teams, fixtures]);
  const setSlot = (index: number, id: string) => setSelected((current) => current.map((value, slot) => slot === index ? id : value));
  return <><section className="page-header"><div><p className="eyebrow">Decisión lado a lado</p><h1>Comparador</h1><p>Hasta cuatro jugadores, con titularidad, Tier, rendimiento disponible y calendario.</p></div><div className="header-stat"><strong>{selectedPlayers.length}</strong><span>jugadores</span></div></section><div className="compare-selectors">{Array.from({ length: 4 }, (_, index) => <label key={index}><span>Jugador {index + 1}</span><select value={selected[index] ?? ""} onChange={(event) => { const id = event.target.value; setSelected((current) => id ? [...current.slice(0, index), id, ...current.slice(index + 1)] : current.filter((_, slot) => slot !== index)); }}><option value="">Sin seleccionar</option>{players.map((player) => <option disabled={selected.includes(player.id) && selected[index] !== player.id} key={player.id} value={player.id}>{player.position} · {player.name} · {player.team.shortName}</option>)}</select></label>)}</div><div className="compare-grid">{selectedPlayers.map((player, index) => { const recommendation = recommendationById.get(player.id); return <article className="compare-card" key={player.id}><header><span className={`tier-badge tier-${recommendation?.tier.replace("+", "plus").toLowerCase()}`}>{recommendation?.tier ?? "NR"}</span><button className={watched.has(player.id) ? "watched" : ""} onClick={() => toggle(player.id)} type="button">★</button><Link href={`/player/${player.slug}`}><h2>{player.name}</h2></Link><p>{player.position} · {player.team.name}</p></header><div className="compare-primary"><span><b>{recommendation?.startingProbability === null ? "—" : `${recommendation?.startingProbability}%`}</b><small>Prob. jugar</small></span><span><b>{recommendation?.recommendationScore ?? "—"}</b><small>Score</small></span></div><dl><div><dt>Minutos</dt><dd>{metric(player.minutes)}</dd></div><div><dt>Puntos</dt><dd>{metric(player.fantasyPoints)}</dd></div><div><dt>Forma</dt><dd>{metric(player.form, 1)}</dd></div><div><dt>xGI</dt><dd>{metric(player.xgi, 2)}</dd></div></dl><section><h3>Próximos partidos</h3>{(upcoming.get(player.team.id) ?? []).map((fixture) => { const opponent = fixture.homeTeam.id === player.team.id ? fixture.awayTeam : fixture.homeTeam; return <span className="compare-fixture" key={fixture.id}><b>J{fixture.round}</b>{fixture.homeTeam.id === player.team.id ? "LOC" : "VIS"} · {opponent.shortName}</span>; })}{!(upcoming.get(player.team.id)?.length) && <p>Calendario no disponible.</p>}</section><details><summary>Explicación</summary><ul>{recommendation?.reasons.map((reason) => <li key={reason}>{reason}</li>)}{recommendation?.risks.map((risk) => <li className="risk" key={risk}>{risk}</li>)}</ul></details>{index >= 2 && <button className="remove-compare" onClick={() => { setSlot(index, ""); setSelected((current) => current.filter((id) => id !== player.id)); }} type="button">Quitar</button>}</article>; })}</div></>;
}
