import type { Metadata } from "next";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";

export const metadata: Metadata = { title: "Metodología", description: "Fuentes, límites y funcionamiento analítico de Hypermociones." };

export default function MethodologyPage() {
  return <AppShell active="methodology">
    <section className="page-header"><div><p className="eyebrow">Transparencia del producto</p><h1>Metodología</h1><p>Qué sabemos, qué introduce el usuario y qué todavía no podemos calcular.</p></div></section>
    <div className="methodology-grid"><section className="panel"><span className="method-number">01</span><p className="eyebrow">Datos deportivos</p><h2>Catálogo 2026/27</h2><p>Los nombres, equipos, posiciones, datos biográficos y calendario cargados proceden del snapshot identificado como RFEF. Cada vista muestra la procedencia y fecha de importación.</p><ul><li>Los valores ausentes se conservan como no disponibles.</li><li>No convertimos campos desconocidos en cero.</li><li>Los adaptadores externos están separados del dominio.</li></ul></section><section className="panel"><span className="method-number">02</span><p className="eyebrow">Disponibilidad</p><h2>Partes con fuente</h2><p>Lesiones, dudas y sanciones pueden registrarse por jornada indicando motivo, fuente, enlace y grado de confirmación.</p><ul><li>Los partes locales no se presentan como datos oficiales del proveedor.</li><li>Lesionados y sancionados se excluyen del optimizador.</li><li>Las dudas reciben una penalización visible.</li></ul></section><section className="panel"><span className="method-number">03</span><p className="eyebrow">Optimización</p><h2>Decisión explicable</h2><p>El motor maximiza un índice de decisión respetando formación, posiciones, límite por club y disponibilidad. Los pesos están en el dominio y tienen pruebas automatizadas.</p><ul><li>Usa proyección manual cuando existe.</li><li>Si no existe, combina solo señales disponibles.</li><li>No suma puntos esperados si falta la proyección de un titular.</li></ul></section><section className="panel"><span className="method-number">04</span><p className="eyebrow">Privacidad</p><h2>Estado en tu dispositivo</h2><p>Mi equipo, alineaciones e incidencias se guardan actualmente en el almacenamiento del navegador. No se envían a una cuenta ni a una base de datos remota.</p><ul><li>Puedes exportar copias JSON.</li><li>Borrar los datos del navegador elimina el estado local.</li><li>La futura sincronización requerirá autenticación y política de privacidad.</li></ul></section></div>
    <div className="methodology-actions"><Link className="button button-primary" href="/my-team">Probar el optimizador →</Link><Link className="button" href="/availability">Revisar disponibilidad</Link></div>
  </AppShell>;
}
